// <auto-generated />
using System;
using JustCommerce.Persistence.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JustCommerce.Persistence.Migrations
{
    [DbContext(typeof(JustCommerceDbContext))]
    [Migration("20220701145740_Migration_Change_In_Identity_Table")]
    partial class Migration_Change_In_Identity_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JustCommerce.Domain.Entities.Article.ArticleCategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("IconPath")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ArticleCategory", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Article.ArticleCategoryLangEntity", b =>
                {
                    b.Property<Guid>("ArticleCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("ArticleCategoryId", "LanguageId");

                    b.HasIndex("LanguageId")
                        .IsUnique();

                    b.ToTable("ArticleCategoryLang", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Article.ArticleCategoryRelatedEntity", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ArticleId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ArticleCategoryRelated", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Article.ArticleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("IconPath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Article", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Article.ArticleLangEntity", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("KeyWords")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ShortContent")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("ArticleId", "LanguageId");

                    b.HasIndex("LanguageId")
                        .IsUnique();

                    b.ToTable("ArticleLang", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Article.ArticleRelatedProductEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleRelatedProduct", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Category.CategoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("OrderValue")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ShopId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Category.CategoryLangEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryLang", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Common.ProductCategoryEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategory", "common");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Company.ShopEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Shop", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("83e84e94-b1ee-4cbf-be40-daea69347600"),
                            AddressLine = "Karpia 22F/59",
                            City = "Poznan",
                            Country = "Poland",
                            Email = "jablonskidawid0202@gmail.com",
                            FullName = "Data-Sharp Dawid Jabłoński",
                            IsActive = false,
                            Name = "DataSharp",
                            State = "Wielkopolska",
                            Zip = "61-619"
                        },
                        new
                        {
                            Id = new Guid("6cef7328-534d-4699-98af-8779fba7d3a1"),
                            AddressLine = "Polna 7",
                            City = "Przytoczna",
                            Country = "Poland",
                            Email = "kontakt@emagazynowo.pl",
                            FullName = "eMagazynowo Dawid Jabłoński",
                            IsActive = false,
                            Name = "eMagazynowo",
                            State = "Lubuskie",
                            Zip = "66-340"
                        });
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Email.EmailAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ImapLogin")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImapPassword")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImapPort")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ImapServer")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Pop3Login")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Pop3Password")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Pop3Port")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Pop3Server")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SmtpLogin")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SmtpPassword")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SmtpPort")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SmtpServer")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("EmailAccount", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("014e3b4b-e2a7-4499-8c82-a905b7b086e2"),
                            EmailAddress = "kontakt@emagazynowo.pl",
                            ImapLogin = "kontakt@emagazynowo.pl",
                            ImapPassword = "kaHBV(.q4F",
                            ImapPort = "143",
                            ImapServer = "serwer2299342.home.pl",
                            Name = "Ogolne",
                            Pop3Password = "",
                            Pop3Port = "1",
                            Pop3Server = "",
                            ShopId = new Guid("6cef7328-534d-4699-98af-8779fba7d3a1"),
                            SmtpLogin = "",
                            SmtpPassword = "",
                            SmtpPort = "1",
                            SmtpServer = ""
                        });
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Email.EmailTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("EmailAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmailAccountId");

                    b.HasIndex("ShopId");

                    b.ToTable("EmailTemplate", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cf702e9b-cceb-476f-ba6e-455004ebf588"),
                            Active = true,
                            Email = "kontakt@emagazynowo.pl",
                            EmailAccountId = new Guid("014e3b4b-e2a7-4499-8c82-a905b7b086e2"),
                            EmailName = "eMagazynowo",
                            EmailType = "ConfirmAccount",
                            FilePath = "D:\\Projects\\JustCommerce\\JustCommerce.Backend\\src\\JustCommerce.Api\\Templates\\EmailTemplates\\6cef7328-534d-4699-98af-8779fba7d3a1\\EmailConfirmation.html",
                            Name = "EmailConfirmed",
                            ShopId = new Guid("6cef7328-534d-4699-98af-8779fba7d3a1"),
                            Subject = "eMagazynowo : Potwierdzenie rejestracji"
                        });
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Identity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FtpPhotoFilePath")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumberConfirmed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RegisterSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("varchar(max)");

                    b.Property<Guid?>("SelectedShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User", "identity");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Identity.UserPermissionEntity", b =>
                {
                    b.Property<string>("PermissionDomainName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("PermissionFlagValue")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionDomainName", "PermissionFlagValue", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPermission", "identity");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Identity.UserShopEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "ShopId");

                    b.HasIndex("ShopId");

                    b.ToTable("UserShop", "common");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Language.LanguageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("DefaultLanguage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NameInternational")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NameOrginal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Language", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b80fe531-4bb7-4f2d-a69e-86d8e20602e9"),
                            DefaultLanguage = true,
                            IsActive = true,
                            IsoCode = "PL-pl",
                            NameInternational = "Polish",
                            NameOrginal = "Polski",
                            ShopId = new Guid("6cef7328-534d-4699-98af-8779fba7d3a1")
                        },
                        new
                        {
                            Id = new Guid("87f0f759-323f-477d-886a-0afd7272ccd9"),
                            DefaultLanguage = false,
                            IsActive = true,
                            IsoCode = "EN-en",
                            NameInternational = "English",
                            NameOrginal = "English",
                            ShopId = new Guid("6cef7328-534d-4699-98af-8779fba7d3a1")
                        },
                        new
                        {
                            Id = new Guid("cce919b8-3a08-417f-8eec-cac0b3fa3b31"),
                            DefaultLanguage = true,
                            IsActive = true,
                            IsoCode = "PL-pl",
                            NameInternational = "Polish",
                            NameOrginal = "Polski",
                            ShopId = new Guid("83e84e94-b1ee-4cbf-be40-daea69347600")
                        },
                        new
                        {
                            Id = new Guid("42f64f81-7935-4724-beb4-edc5f6033868"),
                            DefaultLanguage = false,
                            IsActive = true,
                            IsoCode = "EN-en",
                            NameInternational = "English",
                            NameOrginal = "English",
                            ShopId = new Guid("83e84e94-b1ee-4cbf-be40-daea69347600")
                        });
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Notification.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("_Notification");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Notification.UserNotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("_UserNotification");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Notification.UserSubscribedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("_UserSubscribed");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Offer.OfferEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("CompletionTime")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("DiffrentShipmentRecipient")
                        .HasColumnType("bit");

                    b.Property<bool>("EInvoice")
                        .HasColumnType("bit");

                    b.Property<string>("InvoiceRcipientCity")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InvoiceRecipientAdress")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InvoiceRecipientCountry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InvoiceRecipientName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InvoiceRecipientPostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("InvoiceRecipientTaxId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ItemSumPrice")
                        .HasColumnType("decimal");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("OfferNumber")
                        .HasColumnType("int");

                    b.Property<string>("OfferSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OfferStatusType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("SendToClientDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ShipmentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ShipmentPrice")
                        .HasColumnType("decimal");

                    b.Property<string>("ShipmentRecipientAdress")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShipmentRecipientCity")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShipmentRecipientCountry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShipmentRecipientName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShipmentRecipientPostalCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotallPrice")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentMethodId")
                        .IsUnique();

                    b.HasIndex("ShopId");

                    b.HasIndex("Id", "OfferNumber")
                        .IsUnique();

                    b.ToTable("Offer", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Offer.OfferItemEntity", b =>
                {
                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductSellableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GrossPrice")
                        .HasColumnType("decimal");

                    b.Property<decimal>("NettoPrice")
                        .HasColumnType("decimal");

                    b.Property<decimal>("ProducentPrice")
                        .HasColumnType("decimal");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal");

                    b.HasKey("OfferId", "ProductSellableId");

                    b.HasIndex("ProductSellableId");

                    b.ToTable("OfferItem", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Order.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInfo")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("ConfirmOrder")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("datetime");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("DataProcessingAcceptation")
                        .HasColumnType("bit");

                    b.Property<bool>("DifferentShipmentRecipient")
                        .HasColumnType("bit");

                    b.Property<bool>("FastInvoice")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeShipmentRecipientOnInvoice")
                        .HasColumnType("bit");

                    b.Property<bool>("Invoice")
                        .HasColumnType("bit");

                    b.Property<string>("InvoiceEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InvoiceRecipeintName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InvoiceRecipientAddress")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InvoiceRecipientCity")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InvoiceRecipientCountry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InvoiceRecipientPostalCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InvoiceRecipientRegion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InvoiceRecipientTax")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ItemsSumPriceGross")
                        .HasColumnType("decimal");

                    b.Property<Guid>("LanguageVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("NewsletterAcceptation")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("OrderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderNumber"), 1L, 1);

                    b.Property<bool>("OrderPdf")
                        .HasColumnType("bit");

                    b.Property<bool>("Paid")
                        .HasColumnType("bit");

                    b.Property<bool>("PaymentCallSent")
                        .HasColumnType("bit");

                    b.Property<bool>("PaymentReminderSend")
                        .HasColumnType("bit");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentsSum")
                        .HasColumnType("decimal");

                    b.Property<string>("ProformaNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Rated")
                        .HasColumnType("int");

                    b.Property<Guid>("ShipmentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ShipmentPrice")
                        .HasColumnType("decimal");

                    b.Property<string>("ShipmentRecipientAddress")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShipmentRecipientCity")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShipmentRecipientCountry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShipmentRecipientName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ShipmentRecipientPostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ShipmentRecipientRegion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("SmsNotification")
                        .HasColumnType("bit");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("StatueAcceptation")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("TotallPriceGross")
                        .HasColumnType("decimal");

                    b.Property<int?>("TradeCreditDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageVersionId");

                    b.HasIndex("OrderNumber");

                    b.HasIndex("ShipmentMethodId");

                    b.HasIndex("ShopId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Order.OrderItemEntity", b =>
                {
                    b.Property<Guid>("ProductSellableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GrossPrice")
                        .HasColumnType("decimal");

                    b.Property<decimal>("NettoPrice")
                        .HasColumnType("decimal");

                    b.Property<decimal>("ProducentPrice")
                        .HasColumnType("decimal");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal");

                    b.HasKey("ProductSellableId", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Product.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("AvailabilityType")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MiniaturePhoto")
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("Newsletter")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Top")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("ShopId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Product.ProductFileEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ProductId", "PhotoPath");

                    b.HasIndex("Id");

                    b.ToTable("ProductFile", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Product.ProductLangEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ImageDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("IsoCode")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MetaTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductPropertyJson")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Synonyms")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductLang", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Product.ProductSellableEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("EanCode")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<decimal>("GrossPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal")
                        .HasDefaultValue(0m);

                    b.Property<string>("IconPath")
                        .HasColumnType("varchar(max)");

                    b.Property<decimal>("NettoPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("OldPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ProducentPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal")
                        .HasDefaultValue(0m);

                    b.Property<string>("ProductColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductNumber")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSellable", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.ProductType.ProductTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("ProductType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8539176a-3578-48e1-a2d7-3cce1389c762"),
                            Name = "Pojemniki",
                            ShopId = new Guid("6cef7328-534d-4699-98af-8779fba7d3a1")
                        },
                        new
                        {
                            Id = new Guid("371b379b-3ff4-4523-bd15-b545e185b97c"),
                            Name = "Regały",
                            ShopId = new Guid("6cef7328-534d-4699-98af-8779fba7d3a1")
                        },
                        new
                        {
                            Id = new Guid("d13b4109-2acd-46f5-bd8b-d7f789fac0e0"),
                            Name = "Maty",
                            ShopId = new Guid("83e84e94-b1ee-4cbf-be40-daea69347600")
                        },
                        new
                        {
                            Id = new Guid("e8d5076f-7501-4bb7-8581-f7f894d7a879"),
                            Name = "Drzwi",
                            ShopId = new Guid("83e84e94-b1ee-4cbf-be40-daea69347600")
                        });
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.ProductType.ProductTypePropertyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("OrderValue")
                        .HasColumnType("int");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("ProductTypeProperty", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.ProductType.ProductTypePropertyLangEntity", b =>
                {
                    b.Property<Guid?>("ProductTypePropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DefualtValue")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasKey("ProductTypePropertyId", "Name", "Value");

                    b.ToTable("ProductTypePropertyLang", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.ShipmentMethod.ShipmentMethodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("OrderValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("ShipmentMethod", (string)null);
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.ShipmentMethod.ShipmentMethodLangEntity", b =>
                {
                    b.Property<Guid>("ShipmentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LangaugeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ShipmentMethodId", "LangaugeId");

                    b.HasIndex("LangaugeId")
                        .IsUnique();

                    b.ToTable("ShipmentMethodLangEntity");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Sms.SmsAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SmsGate")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("Test")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("SmsAccount", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2bbfc7c9-8c9c-4f53-82ef-f7560a463070"),
                            From = "Test",
                            ShopId = new Guid("6cef7328-534d-4699-98af-8779fba7d3a1"),
                            SmsGate = "SmsApi",
                            Test = false,
                            Token = "te"
                        });
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Sms.SmsTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SmsAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SmsType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ShopId");

                    b.HasIndex("SmsAccountId");

                    b.ToTable("SmsTemplate", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("027aa12d-b89d-4993-b4f3-aa15135ebfbc"),
                            Active = true,
                            Name = "OrderCancelled",
                            ShopId = new Guid("6cef7328-534d-4699-98af-8779fba7d3a1"),
                            SmsAccountId = new Guid("2bbfc7c9-8c9c-4f53-82ef-f7560a463070"),
                            SmsType = "OrderCancelled"
                        },
                        new
                        {
                            Id = new Guid("fd60132b-a9a8-4fea-8e71-0a8eea2e62e3"),
                            Active = true,
                            Name = "OrderInProgress",
                            ShopId = new Guid("6cef7328-534d-4699-98af-8779fba7d3a1"),
                            SmsAccountId = new Guid("2bbfc7c9-8c9c-4f53-82ef-f7560a463070"),
                            SmsType = "OrderInProgress"
                        },
                        new
                        {
                            Id = new Guid("c2514d93-4e4e-4e27-bf9d-d0a77db3629b"),
                            Active = true,
                            Name = "OrderSend",
                            ShopId = new Guid("6cef7328-534d-4699-98af-8779fba7d3a1"),
                            SmsAccountId = new Guid("2bbfc7c9-8c9c-4f53-82ef-f7560a463070"),
                            SmsType = "OrderSend"
                        },
                        new
                        {
                            Id = new Guid("2a4bdbb1-c4e5-4b5f-b8f0-36369d2560b1"),
                            Active = true,
                            Name = "OrderPlaced",
                            ShopId = new Guid("6cef7328-534d-4699-98af-8779fba7d3a1"),
                            SmsAccountId = new Guid("2bbfc7c9-8c9c-4f53-82ef-f7560a463070"),
                            SmsType = "OrderPlaced"
                        });
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Sms.SmsTemplateLangEntity", b =>
                {
                    b.Property<Guid>("SmsTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("SmsTemplateId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("SmsTemplateLang", (string)null);

                    b.HasData(
                        new
                        {
                            SmsTemplateId = new Guid("027aa12d-b89d-4993-b4f3-aa15135ebfbc"),
                            LanguageId = new Guid("b80fe531-4bb7-4f2d-a69e-86d8e20602e9"),
                            Text = "OrderCancelled PL"
                        },
                        new
                        {
                            SmsTemplateId = new Guid("027aa12d-b89d-4993-b4f3-aa15135ebfbc"),
                            LanguageId = new Guid("87f0f759-323f-477d-886a-0afd7272ccd9"),
                            Text = "OrderCancelled EN"
                        },
                        new
                        {
                            SmsTemplateId = new Guid("fd60132b-a9a8-4fea-8e71-0a8eea2e62e3"),
                            LanguageId = new Guid("b80fe531-4bb7-4f2d-a69e-86d8e20602e9"),
                            Text = "OrderInProgress PL"
                        },
                        new
                        {
                            SmsTemplateId = new Guid("fd60132b-a9a8-4fea-8e71-0a8eea2e62e3"),
                            LanguageId = new Guid("87f0f759-323f-477d-886a-0afd7272ccd9"),
                            Text = "OrderInProgress EN"
                        },
                        new
                        {
                            SmsTemplateId = new Guid("c2514d93-4e4e-4e27-bf9d-d0a77db3629b"),
                            LanguageId = new Guid("b80fe531-4bb7-4f2d-a69e-86d8e20602e9"),
                            Text = "OrderSend PL"
                        },
                        new
                        {
                            SmsTemplateId = new Guid("c2514d93-4e4e-4e27-bf9d-d0a77db3629b"),
                            LanguageId = new Guid("87f0f759-323f-477d-886a-0afd7272ccd9"),
                            Text = "OrderSend EN"
                        },
                        new
                        {
                            SmsTemplateId = new Guid("2a4bdbb1-c4e5-4b5f-b8f0-36369d2560b1"),
                            LanguageId = new Guid("b80fe531-4bb7-4f2d-a69e-86d8e20602e9"),
                            Text = "OrderPlaced PL"
                        },
                        new
                        {
                            SmsTemplateId = new Guid("2a4bdbb1-c4e5-4b5f-b8f0-36369d2560b1"),
                            LanguageId = new Guid("87f0f759-323f-477d-886a-0afd7272ccd9"),
                            Text = "OrderPlaced EN"
                        });
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Article.ArticleCategoryEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Company.ShopEntity", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Article.ArticleCategoryLangEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Article.ArticleCategoryEntity", "ArticleCategory")
                        .WithMany("ArticleCategoryLang")
                        .HasForeignKey("ArticleCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.Language.LanguageEntity", "Language")
                        .WithOne()
                        .HasForeignKey("JustCommerce.Domain.Entities.Article.ArticleCategoryLangEntity", "LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleCategory");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Article.ArticleCategoryRelatedEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Article.ArticleEntity", "Article")
                        .WithMany("ArticleCategoryRelated")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.Article.ArticleCategoryEntity", "Category")
                        .WithMany("ArticleCategoryRelated")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Article.ArticleEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Company.ShopEntity", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Article.ArticleLangEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Article.ArticleEntity", "Article")
                        .WithMany("ArticleLang")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.Language.LanguageEntity", "Language")
                        .WithOne()
                        .HasForeignKey("JustCommerce.Domain.Entities.Article.ArticleLangEntity", "LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Article.ArticleRelatedProductEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Article.ArticleEntity", "Article")
                        .WithMany("ArticleRelatedProduct")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.Product.ProductEntity", "Product")
                        .WithMany("ArticleRelatedProduct")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Category.CategoryEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Category.CategoryEntity", "Parent")
                        .WithMany("ChildCategory")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("JustCommerce.Domain.Entities.Company.ShopEntity", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Category.CategoryLangEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Category.CategoryEntity", "Category")
                        .WithMany("CategoryLang")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Common.ProductCategoryEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Category.CategoryEntity", "Category")
                        .WithMany("ProductCategory")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.Product.ProductEntity", "Product")
                        .WithMany("ProductCategory")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Email.EmailAccountEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Company.ShopEntity", "Shop")
                        .WithMany("EmailAccount")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Email.EmailTemplateEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Email.EmailAccountEntity", "EmailAccount")
                        .WithMany("EmailTemplate")
                        .HasForeignKey("EmailAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.Company.ShopEntity", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EmailAccount");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Identity.UserPermissionEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Identity.UserEntity", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Identity.UserShopEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Company.ShopEntity", "Shop")
                        .WithMany("AllowedUser")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.Identity.UserEntity", "User")
                        .WithMany("AllowedShop")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Language.LanguageEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Company.ShopEntity", "Shop")
                        .WithMany("Language")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Notification.UserNotificationEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Identity.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Notification.UserSubscribedEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Identity.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Offer.OfferEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.ShipmentMethod.ShipmentMethodEntity", "ShipmentMethod")
                        .WithOne()
                        .HasForeignKey("JustCommerce.Domain.Entities.Offer.OfferEntity", "ShipmentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.Company.ShopEntity", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ShipmentMethod");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Offer.OfferItemEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Offer.OfferEntity", "Offer")
                        .WithMany("OfferItem")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.Product.ProductSellableEntity", "ProductSellable")
                        .WithMany("OfferItem")
                        .HasForeignKey("ProductSellableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("ProductSellable");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Order.OrderEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Language.LanguageEntity", "LanguageVersion")
                        .WithMany()
                        .HasForeignKey("LanguageVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.ShipmentMethod.ShipmentMethodEntity", "ShipmentMethod")
                        .WithMany()
                        .HasForeignKey("ShipmentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.Company.ShopEntity", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LanguageVersion");

                    b.Navigation("ShipmentMethod");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Order.OrderItemEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Order.OrderEntity", "Order")
                        .WithMany("OrderItem")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.Product.ProductSellableEntity", "ProductSellable")
                        .WithMany("OrderItem")
                        .HasForeignKey("ProductSellableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductSellable");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Product.ProductEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.ProductType.ProductTypeEntity", "ProductType")
                        .WithMany("Product")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.Company.ShopEntity", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProductType");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Product.ProductFileEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Product.ProductEntity", "Product")
                        .WithMany("ProductFile")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Product.ProductLangEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Product.ProductEntity", "Product")
                        .WithMany("ProductLang")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Product.ProductSellableEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Product.ProductEntity", "Product")
                        .WithMany("ProductSellable")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.ProductType.ProductTypeEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Company.ShopEntity", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.ProductType.ProductTypePropertyEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.ProductType.ProductTypeEntity", "ProductType")
                        .WithMany("ProductTypeProperty")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.ProductType.ProductTypePropertyLangEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.ProductType.ProductTypePropertyEntity", "ProductTypeProperty")
                        .WithMany("ProductTypePropertyLang")
                        .HasForeignKey("ProductTypePropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductTypeProperty");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.ShipmentMethod.ShipmentMethodLangEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Language.LanguageEntity", "Language")
                        .WithOne()
                        .HasForeignKey("JustCommerce.Domain.Entities.ShipmentMethod.ShipmentMethodLangEntity", "LangaugeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.ShipmentMethod.ShipmentMethodEntity", "ShipmentMethod")
                        .WithMany("ShipmentMethodLang")
                        .HasForeignKey("ShipmentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("ShipmentMethod");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Sms.SmsAccountEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Company.ShopEntity", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Sms.SmsTemplateEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Company.ShopEntity", "Shop")
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.Sms.SmsAccountEntity", "SmsAccount")
                        .WithMany("SmsTemplate")
                        .HasForeignKey("SmsAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Shop");

                    b.Navigation("SmsAccount");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Sms.SmsTemplateLangEntity", b =>
                {
                    b.HasOne("JustCommerce.Domain.Entities.Language.LanguageEntity", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JustCommerce.Domain.Entities.Sms.SmsTemplateEntity", "SmsTemplate")
                        .WithMany("SmsTemplateLang")
                        .HasForeignKey("SmsTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("SmsTemplate");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Article.ArticleCategoryEntity", b =>
                {
                    b.Navigation("ArticleCategoryLang");

                    b.Navigation("ArticleCategoryRelated");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Article.ArticleEntity", b =>
                {
                    b.Navigation("ArticleCategoryRelated");

                    b.Navigation("ArticleLang");

                    b.Navigation("ArticleRelatedProduct");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Category.CategoryEntity", b =>
                {
                    b.Navigation("CategoryLang");

                    b.Navigation("ChildCategory");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Company.ShopEntity", b =>
                {
                    b.Navigation("AllowedUser");

                    b.Navigation("EmailAccount");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Email.EmailAccountEntity", b =>
                {
                    b.Navigation("EmailTemplate");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Identity.UserEntity", b =>
                {
                    b.Navigation("AllowedShop");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Offer.OfferEntity", b =>
                {
                    b.Navigation("OfferItem");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Order.OrderEntity", b =>
                {
                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Product.ProductEntity", b =>
                {
                    b.Navigation("ArticleRelatedProduct");

                    b.Navigation("ProductCategory");

                    b.Navigation("ProductFile");

                    b.Navigation("ProductLang");

                    b.Navigation("ProductSellable");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Product.ProductSellableEntity", b =>
                {
                    b.Navigation("OfferItem");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.ProductType.ProductTypeEntity", b =>
                {
                    b.Navigation("Product");

                    b.Navigation("ProductTypeProperty");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.ProductType.ProductTypePropertyEntity", b =>
                {
                    b.Navigation("ProductTypePropertyLang");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.ShipmentMethod.ShipmentMethodEntity", b =>
                {
                    b.Navigation("ShipmentMethodLang");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Sms.SmsAccountEntity", b =>
                {
                    b.Navigation("SmsTemplate");
                });

            modelBuilder.Entity("JustCommerce.Domain.Entities.Sms.SmsTemplateEntity", b =>
                {
                    b.Navigation("SmsTemplateLang");
                });
#pragma warning restore 612, 618
        }
    }
}
